# Use an official Python runtime as a parent image
FROM node:13.8.0-buster-slim
RUN apt-get update && apt-get install -y \
    python3 make build-essential gosu git \
 && rm -rf /var/lib/apt/lists/*

ENV PATH $PATH:env/bin
ENV PYTHON python3
# we do not want node to run as id 1000
RUN groupmod -g 999 node && usermod -u 999 -g 999 node
RUN useradd --create-home application
USER application
COPY --chown=application frontend /opt/frontend
WORKDIR /opt/frontend
ENV FRONTEND_ASSSET_ROOT_DIR /opt/frontend/static_build
RUN cd /opt/frontend/ziggurat_cms_front_admin/static_src; yarn
RUN cd /opt/frontend/ziggurat_cms_front_admin/static_src; yarn bower
RUN cd /opt/frontend/ziggurat_cms_front_admin/static_src; yarn build
RUN cd /opt/frontend/ziggurat_cms_front_front/static_src; yarn
RUN cd /opt/frontend/ziggurat_cms_front_front/static_src; yarn bower
RUN cd /opt/frontend/ziggurat_cms_front_front/static_src; yarn build
RUN cd /opt/frontend/ziggurat_cms_template_podswierkiem/static_src; yarn
RUN cd /opt/frontend/ziggurat_cms_template_podswierkiem/static_src; yarn bower
RUN cd /opt/frontend/ziggurat_cms_template_podswierkiem/static_src; yarn build
COPY docker-entrypoint-static.sh /opt/docker-entrypoint-static.sh
USER root
ENTRYPOINT ["/opt/docker-entrypoint-static.sh"]
CMD ["yarn", "dev"]
