version: '3.2'
services:
  web:
    stdin_open: true
    tty: true
    build: .
    ports:
      - "6543:6543"
    environment:
      SQLALCHEMY_URL: postgresql://test:test@ziggurat_cms_db_1:5432/ziggurat_cms
      REDIS_DOGPILE_URL: redis://ziggurat_cms_redis_1:6379/0
      REDIS_SESSIONS_URL: redis://ziggurat_cms_redis_1:6379/0
      CELERY_BROKER_URL: redis://ziggurat_cms_redis_1:6379/1
      APP_ENV: development
#      USER_UID: 1000
#      USER_GID: 1000
    volumes:
      - type: bind
        source: ./backend
        target: /opt/application
        read_only: true
      - type: volume
        source: rundir
        target: /opt/rundir
    networks:
      - podswierkiem
    depends_on:
      - db
      - redis
  statics_admin:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.static
    environment:
      FRONTEND_ASSSET_ROOT_DIR: "/opt/rundir/static"
      STATIC_DIR: /opt/frontend/ziggurat_cms_front_admin/static_src
    volumes:
      - type: bind
        source: ./frontend
        target: /opt/frontend
      - type: volume
        source: rundir
        target: /opt/rundir
  statics_front:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.static
    environment:
      FRONTEND_ASSSET_ROOT_DIR: "/opt/rundir/static"
      STATIC_DIR: /opt/frontend/ziggurat_cms_front_front/static_src
    volumes:
      - type: bind
        source: ./frontend
        target: /opt/frontend
      - type: volume
        source: rundir
        target: /opt/rundir
  statics_template:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.static
    environment:
      FRONTEND_ASSSET_ROOT_DIR: "/opt/rundir/static"
      STATIC_DIR: /opt/frontend/ziggurat_cms_template_podswierkiem/static_src
    volumes:
      - type: bind
        source: ./frontend
        target: /opt/frontend
      - type: volume
        source: rundir
        target: /opt/rundir
