version: '3.2'
services:
  web:
    stdin_open: true
    tty: true
    build: .
    ports:
      - "6543:6543"
    environment:
      APP_ENV: production
    volumes:
      - type: volume
        source: rundir
        target: /opt/rundir
    networks:
      - podswierkiem
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.2
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres

    volumes:
      - type: bind
        source: ./docker/docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
        read_only: true
      - type: volume
        source: pg_data
        target: /var/lib/postgresql/data
    networks:
      - podswierkiem
  redis:
    image: redis:5.0.8
    ports:
      - "6379"
    networks:
      - podswierkiem
    volumes:
      - type: bind
        source: ./docker/redis/redis.conf
        target: /usr/local/etc/redis/redis.conf
        read_only: true
volumes:
  logvolume01: {}
  rundir: {}
  backend: {}
  frontend: {}
  pg_data: {}
networks:
  podswierkiem:
